# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 97eecc3d57fc595d917bb0ffa29dd282ce2787e325d54d8e45033f17ec37bbdda50e626f91054b0cf7ca02e66fef37a674db1176f1244717753464a47f8f492a

test:
  secret_key_base: e8fc7cb8d181646482b8b61ca28507324993a6d2a4fd726bb5f63a03a02ab1f549e7899aef213878d04b7dd320dc60f3cb34ef21e63283d280b550f568f641f8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
